name: Deploy to Render

# Chỉ kích hoạt khi workflow "Calculate CI" hoàn thành
on:
  workflow_run:
    workflows: ["Calculate CI"] # Phải khớp với `name:` trong CI file
    types:
      - completed # Chạy khi workflow kết thúc (dù thành công hay thất bại)

jobs:
  deploy:
    # Chỉ deploy nếu CI kết thúc thành công (passed)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
